Transform: AWS::Serverless-2016-10-31
Resources:
  CalcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CalcFunction
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /products
      Handler: index.handler
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs16.x
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CalcFunction739b288bDepLayer
    Metadata:
      SamResourceId: CalcFunction
  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PutProductFunction
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /products
      Handler: index.handler
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs16.x
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.PutProductFunctionb4f5bc59DepLayer
    Metadata:
      SamResourceId: PutProductFunction
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      TableName: products
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /home/daniel/shop/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
