Description: Aspan shared resources

Resources:
  InfrastructureBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${AWS::StackName}-infra
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldObjects
            Status: Enabled
            ExpirationInDays: 30
          - Id: IntelligentTieringRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING

  InfrastructureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfrastructureBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:*
            Effect: Allow
            Resource: !Sub ${InfrastructureBucket.Arn}/*
            Principal: "*"

  NotificationTopic:
    Type: AWS::SNS::Topic

  NotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref NotificationTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:Receive
            Resource: !Ref NotificationTopic
            Condition:
              StringEquals:
                aws:SourceOwner: !Sub ${AWS::AccountId}
          - Effect: Allow
            Sid: AWSCodeStarNotifications_publish
            Principal:
              Service: codestar-notifications.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref NotificationTopic
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      MfaConfiguration: "ON"
      UsernameAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool

Outputs:
  InfrastructureBucketName:
    Value: !Ref InfrastructureBucket
    Export:
      Name: InfrastructureBucketName

  InfrastructureBucketArn:
    Value: !GetAtt InfrastructureBucket.Arn
    Export:
      Name: InfrastructureBucketArn

  NotificationTopicArn:
    Value: !Ref NotificationTopic
    Export:
      Name: NotificationTopicArn

  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: CognitoUserPoolId

  CognitoUserPoolArn:
    Value: !GetAtt CognitoUserPool.Arn

  CognitoUserPoolProviderName:
    Value: !GetAtt CognitoUserPool.ProviderName

  CognitoUserPoolProviderURL:
    Value: !GetAtt CognitoUserPool.ProviderURL
    Export:
      Name: CognitoUserPoolProviderURL

  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: CognitoUserPoolClientId
