Transform: AWS::Serverless-2016-10-31

Resources:
  CalcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /products
      Handler: index.handler
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs16.x

  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /products
      Handler: index.handler
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs16.x

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      TableName: "products"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
