Transform: AWS::Serverless-2016-10-31

Resources:
  CalcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /products
      Handler: index.handler
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs14.x
